### PR TITLE
update consisid readme

### PR DESCRIPTION
**Pull request by SHYuanBest**
https://github.com/user-attachments/assets/501d71ef-0e71-4ae9-bceb-51cc18fa33d8

### CODE REVIEW

**Comment by SHYuanBest** [comment]
@LiewFeng have update

**Comment by LiewFeng** [comment]
It seems there are typos in thresh and speedup.

**Comment by SHYuanBest** [comment]
> It seems there are typos in thresh and speedup.

oh, have fixed.

**Comment by LiewFeng** [comment]
Thanks! Merged.

**Pull request merged**
