### PR TITLE
Add support for ConsisID

### PR DESCRIPTION
**Pull request by SHYuanBest**
@LiewFeng Thanks for your great work. I have adapted the ConsisID to TeaCache and used CogVideoX-5B's coefficients directly, and the results all looked normal.

Page: https://pku-yuangroup.github.io/ConsisID/
Code: https://github.com/PKU-YuanGroup/ConsisID
Demo: https://huggingface.co/spaces/BestWishYsh/ConsisID-preview-Space

### CODE REVIEW

**Comment by SHYuanBest** [comment]
Original:

https://github.com/user-attachments/assets/24634378-63db-4041-9b89-ea1d7494f827

rel_l1_thresh = 0.1:

https://github.com/user-attachments/assets/75179fce-a03b-4f21-8f2a-8c5675714d4f

rel_l1_thresh = 0.15:

https://github.com/user-attachments/assets/255f5b4c-4ba0-480a-9f91-3b0588bc9e63

rel_l1_thresh = 0.2:

https://github.com/user-attachments/assets/0092192d-61cb-4cdd-8bcb-1d74240c2637

**Comment by LiewFeng** [comment]
Great! Thanks a lot! And
1) Please do not modify requirements.txt. It's for VideoSys. You can add another requirements.txt under TeaCache4ConsisID if necessary.
2) Please modify '' to '' in line 1 in TeaCache4ConsisID/README.md

**Comment by SHYuanBest** [comment]
Thanks for your review, I have update the PR.

**Comment by LiewFeng** [comment]
Thanks! Merged.

**Comment by LiewFeng** [comment]
Hi, @SHYuanBest . 
1) I fix a small bug of TeaCache, see [here](https://github.com/LiewFeng/TeaCache/commit/27ecce2b3a4660f48cc9614b4418ddc5d772fc47).
2) Could you add a video in the README of TeaCache4ConsisID to show the demonstrate the results, similar to [TeaCache4HunyuanVideo](https://github.com/LiewFeng/TeaCache/tree/main/TeaCache4HunyuanVideo)?

**Pull request merged**
